name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  cd:
    runs-on: sg
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: CI
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
          run_number: ${{ github.event.workflow_run.run_number }}
          name: identicons-artifact-${{ github.event.workflow_run.head_commit.id }}.zip

      - name: List file
        run: ls

      - name: Unzip artifact
        run: rm -rf ./dist && unzip identicons-artifact-${{ github.event.workflow_run.head_commit.id }}.zip -d ./dist

      - name: Deploy Test Environment
        run: |
          rsync -a ./dist/ root@frontendtest:/root/release_test/code/identicons_test
          ssh root@frontendtest 'source ~/.zshrc && cd /root/release_test/code/identicons_test && npm run build && npm run reload_test'
        if: github.event.workflow_run.head_branch == 'develop'

      - name: Deploy Production Environment
        run: |
          rsync -a ./dist/ root@frontend:/root/release_prod/code/identicons
          ssh root@frontend 'source ~/.zshrc && cd /root/release_prod/code/identicons && npm run build && npm run reload_production'
        if: github.event.workflow_run.head_branch == 'main'
